# Generated by Django 5.0.1 on 2025-10-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(max_length=50, unique=True)),
                ('org_shortname', models.CharField(max_length=100)),
                ('org_type', models.CharField(blank=True, max_length=100, null=True)),
                ('org_name', models.CharField(max_length=255)),
                ('report_org', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_address', models.TextField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_address', models.TextField(blank=True, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['org_name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('telephone', 'Telephone'), ('mobile', 'Mobile'), ('fax', 'Fax'), ('email', 'Email')], max_length=20)),
                ('contact_value', models.CharField(max_length=255)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='departments.department')),
            ],
            options={
                'db_table': 'department_contacts',
                'ordering': ['dept', 'contact_type'],
            },
        ),
    ]
