# Generated by Django 5.0.1 on 2025-10-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('district_code_ap', models.CharField(max_length=50, unique=True)),
                ('district_code_ind', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['district_name'],
            },
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandal_name', models.CharField(max_length=255)),
                ('mandal_code_ap', models.CharField(max_length=50, unique=True)),
                ('mandal_code_ind', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandals', to='locations.district')),
            ],
            options={
                'db_table': 'mandals',
                'ordering': ['district', 'mandal_name'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=255)),
                ('village_code_ap', models.CharField(max_length=50, unique=True)),
                ('village_code_ind', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='locations.district')),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='locations.mandal')),
            ],
            options={
                'db_table': 'villages',
                'ordering': ['district', 'mandal', 'village_name'],
            },
        ),
    ]
