# Generated by Django 5.0.1 on 2025-10-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(help_text='Type of object being logged (e.g., Item, User, Department)', max_length=50)),
                ('subject_id', models.IntegerField(help_text='ID of the object being logged')),
                ('action', models.CharField(help_text='Action performed (e.g., create, update, delete, verify)', max_length=50)),
                ('status', models.CharField(help_text='Status of the action (e.g., success, failure)', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata about the action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
