# Generated by Django 5.0.1 on 2025-10-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', '-created_at'], name='logs_user_id_5dcf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['subject_type', 'subject_id'], name='logs_subject_f0e30e_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-created_at'], name='logs_created_dfc914_idx'),
        ),
    ]
