# Generated by Django 5.0.1 on 2025-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('perishability', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item Definition',
                'verbose_name_plural': 'Item Definitions',
                'db_table': 'item_info',
                'ordering': ['item_name'],
            },
        ),
    ]
